### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks mod

### ISSUE THREAD

**Issue by Baggytrousers27** [Erfurt92/MagicalJewelry#11]
Magical Jewelry (magicaljewelry) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

magicaljewelry-1.18.2_1.4.0
curios-forge-1.18.2-5.0.6.3
1.18.2 40.0.18

[Crash Log](https://pastebin.com/DsEESJ7a)

**Comment by Erfurt92** [comment]
Fixed with version 1.4.1

**Comment by Baggytrousers27** [comment]
Excellent.
