### ISSUE TITLE
Magical Jewelry tried to use a chest as a living entity which resulted in a crash.

### ISSUE THREAD

**Issue by Romoslayer** [Erfurt92/MagicalJewelry#12]
Magical Jewelry tried to use a chest as a living entity which resulted in a crash.

I am not sure how to reproduce as this seems to happen just randomly.

Magical Jewelry: 1.16.5-1.2.11
forge: 1.16.5-36.2.20

Logs:
[latest.log](https://github.com/Erfurt92/MagicalJewelry/files/8485223/latest.log)

**Comment by Erfurt92** [comment]
I can see that you have a lot of mods installed, makes it hard to figure out. But I have one question, are you using minecarts as entity cramming? Maybe in a gold farm or something?

**Comment by Romoslayer** [comment]
Nope, this was on a fresh world. I usually create new worlds and test new mods on them as I have been making a mod pack for a while anyway, I suspect the mod called loot integrations as this is not the first time this has happened however, the last time the logs file had more to say (luckily I just found that logs file)

This is the one from the last time something similar happened:
[crash-2022-04-05_16.49.49-server.txt](https://github.com/Erfurt92/MagicalJewelry/files/8486082/crash-2022-04-05_16.49.49-server.txt)
.

**Comment by Erfurt92** [comment]
I don't really know that mod. Are you adding loot tables to datapacks, or are the mod doing that by itself?
Both of the logs tell me the same thing that a Chest Minecart is being cast to LivingEntity, which it can't. I do believe I have fixed it, although I'm not sure. I have no idea how it managed to get a Chest Minecart, when it did, and that's what confusing me. What that means is that I have no way of reproducing this and therefore no way to test if I have properly fixed it. I would really like to find the actual cause of the problem so I can test it. However the update, with the fix (hopefully) is out now. If you notice that it's not fixed please reopen and tell me, and I will have another look at it.

**Comment by Romoslayer** [comment]
I believe the loot integrations mod edits vanilla loot tables and adds modded items into them, I will update the mod and will do some testing to see if the same crash occurs, thank you.

**Comment by Romoslayer** [comment]
Seems to be fixed as I have not had a related crash happen since this update, appreciate it.
