### ISSUE TITLE
Empty Chests[BUG]

### ISSUE THREAD

**Issue by MiguelWaffles** [Erfurt92/MagicalJewelry#4]
**Versions (Be specific, do not write "latest"):**
* Magical Jewelry:magicaljewelry-1.15.2_1.0.5.jar
* Curios:
* Forge: 31.2.9

**There might be an incompatibility issue with this "mod"**
Make sure that the issue is only happening with my mod installed.
Test both with and without my mod before making an issue about it!

**Describe the bug**
Empty loot chest in villages / endcity / other mods / nether / mineshafts etc

**To Reproduce**
1. Step 1
2. Step 2
3. Step 3
4. [...]

**Expected behavior**

**Screenshots**

**Additional context**
Crash Log: Please use a paste site like [pastebin](https://pastebin.com/).
[latest.log](https://github.com/Erfurt92/MagicalJewelry/files/4755821/latest.log)

**Comment by Erfurt92** [comment]
I hope this is fixed in version 1.0.6 - not going to close it just yet, as I'm still unsure if it's fixed
