### ISSUE TITLE
[BUG] Crash trying to upgrade diamond armor

### ISSUE THREAD

**Issue by someaddons** [Erfurt92/MagicalJewelry#8]
**Versions (Be specific, do not write "latest"):**
* Magical Jewelry: magicaljewelry-1.16.5_1.2.7.jar
* Curios:
* Forge:

**There might be an incompatibility issue with this "mod"**

**Describe the bug**
Putting diamond armor into the smithing table crashes with your recipe
**To Reproduce**
1. Step 1 Put diamond armor(unenchanted) into a crafting table

**Expected behavior**

**Screenshots**

**Additional context**
Crash Log: Please use a paste site like [pastebin](https://pastebin.com/). https://gist.github.com/stigli/c2c4fd7610b17081000923c3adf951fb

**Comment by Erfurt92** [comment]
I'm aware of this issue, and I have it fixed with the next update

**Comment by Erfurt92** [comment]
Fixed with 1.16.5_1.2.8

**Comment by someaddons** [comment]
nice thanks
